// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw8MKbSPL909iqrjhbEKuT5p0-BnXhZHA',
    appId: '1:324677275380:web:11914ea6bc193fd07818a1',
    messagingSenderId: '324677275380',
    projectId: 'ai-waste-management-834c3',
    authDomain: 'ai-waste-management-834c3.firebaseapp.com',
    storageBucket: 'ai-waste-management-834c3.firebasestorage.app',
    measurementId: 'G-K6FXCQ5EHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdKoWb71Xh3KqnAHzjPcMRWRmZ1cqSag',
    appId: '1:324677275380:android:96fb40b9e45336bd7818a1',
    messagingSenderId: '324677275380',
    projectId: 'ai-waste-management-834c3',
    storageBucket: 'ai-waste-management-834c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9UbMSA47XfMEMIv1QQ1Y3z5YawUdH23U',
    appId: '1:324677275380:ios:2afbc3b80813e3317818a1',
    messagingSenderId: '324677275380',
    projectId: 'ai-waste-management-834c3',
    storageBucket: 'ai-waste-management-834c3.firebasestorage.app',
    androidClientId: '324677275380-r5t4gh6k0lm194850ljacfj86oktoh8k.apps.googleusercontent.com',
    iosClientId: '324677275380-59frdtflb4fntsvqi86njbh1jhbllnuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eco_snap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9UbMSA47XfMEMIv1QQ1Y3z5YawUdH23U',
    appId: '1:324677275380:ios:2afbc3b80813e3317818a1',
    messagingSenderId: '324677275380',
    projectId: 'ai-waste-management-834c3',
    storageBucket: 'ai-waste-management-834c3.firebasestorage.app',
    androidClientId: '324677275380-r5t4gh6k0lm194850ljacfj86oktoh8k.apps.googleusercontent.com',
    iosClientId: '324677275380-59frdtflb4fntsvqi86njbh1jhbllnuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eco_snap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw8MKbSPL909iqrjhbEKuT5p0-BnXhZHA',
    appId: '1:324677275380:web:3be078a71dafb2ba7818a1',
    messagingSenderId: '324677275380',
    projectId: 'ai-waste-management-834c3',
    authDomain: 'ai-waste-management-834c3.firebaseapp.com',
    storageBucket: 'ai-waste-management-834c3.firebasestorage.app',
    measurementId: 'G-NK9K1WMGDT',
  );
}
